### ISSUE TITLE
Add small test cases that we can repeatedly test to evaluate metrics

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/gtc-biodiversity#10]

**Comment by rdnfn** [comment]
Working on the following branch on this issue: [`feature/minimal-test-cases`](https://github.com/ai4er-cdt/gtc-biodiversity/tree/feature/minimal-test-cases)

**Comment by rdnfn** [comment]
Done with PR #21. See https://github.com/ai4er-cdt/gtc-biodiversity/blob/master/src/data_loading/test_data.py.
