### ISSUE TITLE
Create shared interface / architecture

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/gtc-biodiversity#11]

**Comment by Croydon-Brixton** [comment]
For drawing clear interfaces, I would recommend draw.io

**Comment by rdnfn** [comment]
Purpose: create shared interfaces that allow us to mix different algorithm pipelines and make contributing accessible.

Next steps: 
- Add any observations on suitable data types made whilst implementing as comments below
- Revisit more formal definition after first attempts at creating minimal algorithm completed (maybe after 25 Jan),

**Comment by Croydon-Brixton** [comment]
Issue out of date.
