### ISSUE TITLE
Setup model evaluation framework

### ISSUE THREAD

**Issue by rdnfn** [ai4er-cdt/gtc-biodiversity#15]
**Purpose:** we need to setup a rigurous framework to evaluate relative model performance. Whilst we create "metrics", these are part of the model and cannot be directly used to evaluate relative performance between models. How can evaluate models relative to each other? How do we know a model is "good"?

**Possible evaluation methods:**
- Create simple test cases (as in papers such as Fahrig 2003), e.g two circles with increasing distance. See issue #10.
- Pick a metric with ground truth (e.g. average patch size), and evaluate with respect to that ground truth.
- What else?

**TODOs:**
- Check how relative comparison is done in other papers

**Comment by Croydon-Brixton** [comment]
Issue out of date.
