### ISSUE TITLE
Decide on citation style in report

### ISSUE THREAD

**Issue by rdnfn** [ai4er-cdt/gtc-biodiversity#17]
**Description:** I would suggest to change the citation style in the report to an author-year-style. I think it reads significantly better, as you can write something like _"Simon et al. (2021) propose a super cool graph-based method for habitat fragmentation ..."_. Number-based citations can be very tedious to read, and are harder to remember across sections, was it 87 or 78? If you have another preference, feel free to comment below so we can discuss.

**Possible Solution:**
One way to do the author-year-style would be with the following in the preamble (using natbib):
```
\usepackage{natbib}
\bibliographystyle{abbrvnat}
\setcitestyle{authoryear}
```

Then use `\citet{ }` and `\citep{}` to create _Simon et al. (2021)_ and _(Simon et al., 2021)_ respectively. 

For adding the bibliography we would use
```
\bibliography{references}
```

**Comment by sdat2** [comment]
Yeah, so feel free to do this, you can change anything about the bibliography in Theme/referencing.sty as far as I am aware. I agree that replacing numbers with names does help with legibility, particularly if the density of citations isn't too high, and it's a longer report.

**Comment by sdat2** [comment]
I changed the option to `citestyle=authoryear`, but hopefully there's another option which improves the appearance.

**Comment by rdnfn** [comment]
Thanks, I will look into it after the meeting.

**Comment by sdat2** [comment]
Here's a list of styles: <https://www.overleaf.com/learn/latex/biblatex_bibliography_styles>

**Comment by rdnfn** [comment]
I switched it over to natbib now, and it works and looks fine :) Happy to reopen the issue if somebody has another preference.
