### ISSUE TITLE
Precision for calculating adjacent polygons

### ISSUE THREAD

**Issue by Croydon-Brixton** [ai4er-cdt/gtc-biodiversity#23]
**Question:** 
Should we allow for a given epsilon (e.g. `EPS=1e-12`) machine precision when calculating whether polygons `touch` in our build-up of the `GeoGraph`? 

**Context:**
The reason I raise this issue is [this issue in shapely](https://github.com/Toblerity/Shapely/issues/346) here which explains that polygon `touch` operations do not currently implement a buffer against machine precision issues. 
While it seems from that thread that this is not an issue when we use right-angle geometries only (such as our complex polygonized rasters), I do not know this for sure. 

**My take:**
To be on the safe side, and to also support non-right-angle geometries for potential future use cases I think it would be good to implement the option of the epsilon-precision-touches. The trade-off to be considered is the graph-build-up speed. Depending on how much this epsilon-precision-touch might slow down the graph-build up I would make it the default or not. 
@herbiebradley @arduinfindeis what's your take?

![image](https://user-images.githubusercontent.com/19754061/108355499-d0872f00-71e2-11eb-9ca5-019b009eaff0.png)

**Comment by herbiebradley** [comment]
Interesting - we may want to test the speed of doing this. I'm not sure if there are any cases where this makes a difference with our data - I might manually look over the Polesia data graph to see if I can see any.

**Comment by Croydon-Brixton** [comment]
Tolerance was implemented via a buffer operations on polygons for a given graph in #24
