### ISSUE TITLE
Create GeoGraph metrics

### ISSUE THREAD

**Issue by rdnfn** [ai4er-cdt/gtc-biodiversity#35]
**Description:** it would be great to have a diverse set of metrics, for users this will be a key feature of our tool. To make it easy to add new metrics later on, I think it would be a good idea to agree on a unified signature for all GeoGraph metrics. I propose the following:

```python
class Metric(TypedDict):
    """ This class defines a dictionary type for metric.

    Example: {'name': 'average component area', 'value':100, 'unit': 'm^2', 'variant':'component'}
    """
    name: str
    value: float
    unit: str
    variant: str  #e.g. 'graph', 'conventional', 'component'

def get_avg_component_area(graph: geograph.GeoGraph) -> Metric:
```

**Metrics to create:**
(We don't necessarily need all, but a few would be great)

- [x] Average component area
- [x] Number of components
- [x] Average patch area
- [x] Total area
- [x] Percentage of landscape
- [ ] Mean patch isolation (average distance to the next-nearest patch)
- [x] Mean component isolation (average distance to the next-nearest component)

**Additional features:**
- Should we make habitats (pseudo) GeoGraph instances with a df attribute that references the main df of the parent graph (without deep copying)? That way habitat's could be passed directly to metric functions.
- It would be great if we could show changes in metrics along with changes in nodes and polygons via the `GeoGraphTimeline` class. Something like
> Number of components: ⬆️ +10% (from 11 to 14)
> Average component area: ⬇️ -5% (from 100 m^2 to 60m^2)

**Additional info:**
This is roughly where the metrics would go in the UI
![Screenshot 2021-03-02 at 10 34 30](https://user-images.githubusercontent.com/75615911/109639169-c819e700-7b46-11eb-8515-487ee60a2033.png)

**Comment by herbiebradley** [comment]
Looks good! I suggest making `Metric` a dataclass rather than a `TypedDict`, since they have a few advantages (e.g. https://www.reddit.com/r/Python/comments/eplsb1/would_you_prefer_a_data_class_instance_no_methods/feld6vq/).

> Should we make habitats (pseudo) GeoGraph instances with a df attribute that references the main df of the parent graph (without deep copying)? That way habitat's could be passed directly to metric functions.

We can just keep habitats as a single graph object but have a separate `original_index` column in the main df, then all node IDs in the habitat graph will always reference the correct row in the main df indexed by `original_index`. This column is also useful for fixing an issue with the rtree when we call `merge_nodes`, as discussed in the Slack.

**Comment by Croydon-Brixton** [comment]
Here the link to our score card for prioritization:
https://docs.google.com/spreadsheets/d/1p8AKvyMRvFzhOdBWGVHLmOvtWSQdGH8vX0aWK4jnHKc/edit#gid=0

**Comment by rdnfn** [comment]
The core functionality has been implemented, therefore closing this issue.
