### ISSUE TITLE
Regarding Installation 

### ISSUE THREAD

**Issue by rockbusteriitk** [ai4er-cdt/gtc-biodiversity#94]
![IMG-20230722-WA0005](https://github.com/ai4er-cdt/geograph/assets/84172773/28da3135-0e8b-4fb6-87be-be844049ba4f)
Cannot install Geograph. Getting this error.

**Comment by herbiebradley** [comment]
`geograph` is tested and supported on Ubuntu Linux - Windows is not really supported.
But this looks like a GDAL installation issue with rasterio, see: https://rasterio.readthedocs.io/en/stable/installation.html#advanced-installation
